server:
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow

    so-sndbuf: 0
    so-rcvbuf: 0

forward-zone:
    name: "dns.example.com."
    forward-addr: 172.20.0.10

forward-zone:
    name: "."
    forward-addr: 1.1.1.1
    forward-addr: 8.8.8.8
